# This deletes *ALL* Origin and OpenShift Enterprise content installed by
# ansible.  This includes:
#
#    configuration
#    containers
#    example templates and imagestreams
#    images
#    RPMs
---
- hosts: master1.example.com
  become: yes
  tasks:
  - name: set up jenkins
    shell: | 
      oc login -u system:admin
      oc new-project jenkins
      sleep 2
      oc adm policy add-role-to-user edit alice
      oc adm policy add-role-to-user edit bob
      sleep 2
      oc new-app jenkins-persistent --param ENABLE_OAUTH=true --param MEMORY_LIMIT=2Gi --param VOLUME_CAPACITY=4G
      oc adm pod-network make-projects-global jenkins
  - name: set up dev project
    shell: | 
      oc new-project dev
      sleep 2
      oc policy add-role-to-user edit system:serviceaccount:jenkins:jenkins -n dev
      oc adm policy add-role-to-user edit alice
      oc adm policy add-role-to-user edit bob
      oc new-app jboss-eap70-openshift:1.6~https://github.com/wkulhanek/openshift-tasks
      oc expose svc openshift-tasks
      oc set triggers dc openshift-tasks --manual
  - name: set up prod project
    shell: | 
      oc new-project prod
      sleep 2
      oc policy add-role-to-user edit system:serviceaccount:jenkins:jenkins -n prod
      oc adm policy add-role-to-user edit alice
      oc adm policy add-role-to-user edit bob
      oc new-app jboss-eap70-openshift:1.6~https://github.com/wkulhanek/openshift-tasks
      oc expose svc openshift-tasks
      oc set triggers dc openshift-tasks --manual
