# This deletes *ALL* Origin and OpenShift Enterprise content installed by
# ansible.  This includes:
#
#    configuration
#    containers
#    example templates and imagestreams
#    images
#    RPMs
---
- hosts: all
  become: yes
  tasks:
  - name: assure hostname
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
     # FIXME: this sets locahost as hostname on the localhost, but since this host is only jumphost i do not care..
    # GOOD: All other hosts now knwo who they are!

  - name: adjust timezone
    shell: "timedatectl set-timezone Europe/Berlin"

  - name: point resolver to own dns server
    shell: |
      nmcli con modify "System eth0" -ipv4.dns 192.168.0.1
      nmcli con modify "System eth0" ipv4.ignore-auto-dns yes
      nmcli con modify "System eth0" ipv4.dns 192.168.0.254

  - name: restart network
    systemd:
       state: restarted
       name: network

