---
# tasks file for prep_git

- name: create project base dir
  file:
    path: /root/project
    state: directory
    mode: 0755
  become: true


- name: clone homework repository
  git:
    repo: 'https://github.com/mschreie/homework'
    dest: /root/project/homework
    clone: yes
    update: yes
  become: true


